# Generated by Django 5.0.3 on 2024-04-05 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_rename_event_date_event_event_date_and_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventreview',
            old_name='product',
            new_name='event',
        ),
    ]
