# Generated by Django 5.0.3 on 2024-04-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_rename_product_eventreview_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_date_and_time',
            new_name='event_date',
        ),
        migrations.AddField(
            model_name='event',
            name='event_time',
            field=models.TimeField(default= "00:00"),
            preserve_default=False,
        ),
    ]
