# Generated by Django 5.0.3 on 2024-03-27 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_post_posted_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='comment',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='comment_date',
            new_name='review_date',
        ),
    ]
