# Generated by Django 5.0.3 on 2024-03-29 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_post_posted_time_post_user_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='posted_time',
        ),
    ]
