# Generated by Django 5.0.3 on 2024-03-29 21:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_post_posted_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posted_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
