# Generated by Django 5.0.3 on 2024-03-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_rating_rate_alter_rating_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='Rating',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='Rate',
        ),
        migrations.AddField(
            model_name='rating',
            name='rate',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=0),
        ),
    ]
