# Generated by Django 5.0.3 on 2024-04-04 07:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_post_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='post',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='post',
            new_name='product',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('product', 'user')},
        ),
    ]
