# Generated by Django 5.0.3 on 2024-04-06 07:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_product_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='ProductRating',
        ),
        migrations.RenameModel(
            old_name='Review',
            new_name='ProductReview',
        ),
    ]
